Add a function to calculate checksums
This will use either GNU md5sum or the BSD md5 command to verify.

diff --git a/gitbucket-update b/gitbucket-update
--- a/gitbucket-update
+++ b/gitbucket-update
@@ -7,6 +7,15 @@
 # Matthew Malensek <matt@malensek.net>
 ################################################################################
 
+checksum() {
+    if command -v md5sum > /dev/null 2>&1; then
+        md5sum "${1}" | awk '{ print $1 }'
+    elif command -v md5 > /dev/null 2>&1; then
+        md5 -q "${1}"
+    else
+        >&2 echo "Error: no md5 utility found!"
+    fi
+}
 
 dir="${1}"
 if [[ -z "${dir}" ]]; then
